name: taste-buddy

services:
  frontend:
    image: tb-frontend
    build:
      context: frontend
    ports:
      - 8081:8081

  backend:
    image: tb-backend
    build:
      context: backend
    links:
      - database
      - elasticsearch
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "mysql://root:0000@database:3306/tastebuddy"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - 3307:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mysql-db:/var/lib/mysql

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
      environment: 
        ES_JAVA_OPTS: -Xms2g -Xmx2g
        bootstrap.memory_lock: true
        discovery.type: single-node
        xpack.security.enabled: false
        xpack.security.enrollment.enabled: false
      ports:
        - 9200:9200
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    environment:
      XPACK_APM_SERVICEMAPENABLED: "true"
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: aaaaaaaa-c4d3-4a0a-8290-2abcb83ab3aa
    ports:
      - 5601:5601

volumes:
  mysql-db:

networks:
  elastic: